export const countries = [
  {id: "AF", label: "Afghanistan"},
  {id: "AL", label: "Albania"},
  {id: "DZ", label: "Algeria"},
  {id: "AD", label: "Andorra"},
  {id: "AO", label: "Angola"},
  {id: "AI", label: "Anguilla"},
  {id: "AQ", label: "Antarctica"},
  {id: "AR", label: "Argentina"},
  {id: "AM", label: "Armenia"},
  {id: "AW", label: "Aruba"},
  {id: "AU", label: "Australia"},
  {id: "AT", label: "Austria"},
  {id: "AZ", label: "Azerbaijan"},
  {id: "BH", label: "Bahrain"},
  {id: "BS", label: "Bahamas"},
  {id: "BD", label: "Bangladesh"},
  {id: "BB", label: "Barbados"},
  {id: "BY", label: "Belarus"},
  {id: "BE", label: "Belgium"},
  {id: "BZ", label: "Belize"},
  {id: "BJ", label: "Benin"},
  {id: "BM", label: "Bermuda"},
  {id: "BT", label: "Bhutan"},
  {id: "BO", label: "Bolivia"},
  {id: "BA", label: "Bosnia"},
  {id: "BW", label: "Botswana"},
  {id: "BR", label: "Brazil"},
  {id: "BN", label: "Brunei Darussalam"},
  {id: "BG", label: "Bulgaria"},
  {id: "BF", label: "Burkina Faso"},
  {id: "BI", label: "Burundi"},
  {id: "KH", label: "Cambodia"},
  {id: "CM", label: "Cameroon"},
  {id: "CA", label: "Canada"},
  {id: "KY", label: "Cayman Islands"},
  {id: "TD", label: "Chad"},
  {id: "CL", label: "Chile"},
  {id: "CN", label: "China"},
  {id: "CX", label: "Christmas Island"},
  {id: "CO", label: "Colombia"},
  {id: "KM", label: "Comoros"},
  {id: "CG", label: "Congo"},
  {id: "CR", label: "Costa Rica"},
  {id: "HR", label: "Croatia"},
  {id: "CU", label: "Cuba"},
  {id: "CY", label: "Cyprus"},
  {id: "CZ", label: "Czech Republic"},
  {id: "DK", label: "Denmark"},
  {id: "DJ", label: "Djibouti"},
  {id: "DM", label: "Dominica"},
  {id: "DO", label: "Dominican Republic"},
  {id: "EC", label: "Ecuador"},
  {id: "EG", label: "Egypt"},
  {id: "GQ", label: "Equatorial Guinea"},
  {id: "ER", label: "Eritrea"},
  {id: "EE", label: "Estonia"},
  {id: "ET", label: "Ethiopia"},
  {id: "FJ", label: "Fiji"},
  {id: "FI", label: "Finland"},
  {id: "FR", label: "France"},
  {id: "GA", label: "Gabon"},
  {id: "GM", label: "Gambia"},
  {id: "GE", label: "Georgia"},
  {id: "DE", label: "Germany"},
  {id: "GH", label: "Ghana"},
  {id: "GI", label: "Gibraltar"},
  {id: "GR", label: "Greece"},
  {id: "GL", label: "Greenland"},
  {id: "GD", label: "Grenada"},
  {id: "GP", label: "Guadeloupe"},
  {id: "GU", label: "Guam"},
  {id: "GT", label: "Guatemala"},
  {id: "GG", label: "Guernsey"},
  {id: "GN", label: "Guinea"},
  {id: "GY", label: "Guyana"},
  {id: "HT", label: "Haiti"},
  {id: "HN", label: "Honduras"},
  {id: "HK", label: "Hong Kong"},
  {id: "HU", label: "Hungary"},
  {id: "IS", label: "Iceland"},
  {id: "IN", label: "India"},
  {id: "ID", label: "Indonesia"},
  {id: "IR", label: "Iran"},
  {id: "IQ", label: "Iraq"},
  {id: "IE", label: "Ireland"},
  {id: "IL", label: "Israel"},
  {id: "IT", label: "Italy"},
  {id: "JM", label: "Jamaica"},
  {id: "JP", label: "Japan"},
  {id: "JE", label: "Jersey"},
  {id: "JO", label: "Jordan"},
  {id: "KZ", label: "Kazakhstan"},
  {id: "KE", label: "Kenya"},
  {id: "KI", label: "Kiribati"},
  {id: "KR", label: "Korea"},
  {id: "KW", label: "Kuwait"},
  {id: "KG", label: "Kyrgyzstan"},
  {id: "LV", label: "Latvia"},
  {id: "LB", label: "Lebanon"},
  {id: "LS", label: "Lesotho"},
  {id: "LR", label: "Liberia"},
  {id: "LY", label: "Libya"},
  {id: "LT", label: "Lithuania"},
  {id: "LU", label: "Luxembourg"},
  {id: "MO", label: "Macao"},
  {id: "MG", label: "Madagascar"},
  {id: "MW", label: "Malawi"},
  {id: "MY", label: "Malaysia"},
  {id: "MV", label: "Maldives"},
  {id: "ML", label: "Mali"},
  {id: "MT", label: "Malta"},
  {id: "MR", label: "Mauritania"},
  {id: "MU", label: "Mauritius"},
  {id: "MX", label: "Mexico"},
  {id: "MC", label: "Monaco"},
  {id: "MN", label: "Mongolia"},
  {id: "ME", label: "Montenegro"},
  {id: "MS", label: "Montserrat"},
  {id: "MA", label: "Morocco"},
  {id: "MM", label: "Myanmar"},
  {id: "NA", label: "Namibia"},
  {id: "NR", label: "Nauru"},
  {id: "NP", label: "Nepal"},
  {id: "NL", label: "Netherlands"},
  {id: "NZ", label: "New Zealand"},
  {id: "NI", label: "Nicaragua"},
  {id: "NG", label: "Nigeria"},
  {id: "NO", label: "Norway"},
  {id: "OM", label: "Oman"},
  {id: "PK", label: "Pakistan"},
  {id: "PW", label: "Palau"},
  {id: "PS", label: "Palestine"},
  {id: "PA", label: "Panama"},
  {id: "PG", label: "Papua New Guinea"},
  {id: "PY", label: "Paraguay"},
  {id: "PE", label: "Peru"},
  {id: "PH", label: "Philippines"},
  {id: "PL", label: "Poland"},
  {id: "PT", label: "Portugal"},
  {id: "PR", label: "Puerto Rico"},
  {id: "QA", label: "Qatar"},
  {id: "RO", label: "Romania"},
  {id: "RU", label: "Russian Federation"},
  {id: "RW", label: "Rwanda"},
  {id: "BL", label: "Saint Barthélemy"},
  {id: "LC", label: "Saint Lucia"},
  {id: "WS", label: "Samoa"},
  {id: "SM", label: "San Marino"},
  {id: "SA", label: "Saudi Arabia"},
  {id: "SN", label: "Senegal"},
  {id: "RS", label: "Serbia"},
  {id: "SC", label: "Seychelles"},
  {id: "SL", label: "Sierra Leone"},
  {id: "SG", label: "Singapore"},
  {id: "SK", label: "Slovakia"},
  {id: "SI", label: "Slovenia"},
  {id: "SB", label: "Solomon Islands"},
  {id: "SO", label: "Somalia"},
  {id: "ZA", label: "South Africa"},
  {id: "SS", label: "South Sudan"},
  {id: "ES", label: "Spain"},
  {id: "LK", label: "Sri Lanka"},
  {id: "SD", label: "Sudan"},
  {id: "SR", label: "Suriname"},
  {id: "SZ", label: "Swaziland"},
  {id: "SE", label: "Sweden"},
  {id: "CH", label: "Switzerland"},
  {id: "TW", label: "Taiwan"},
  {id: "TJ", label: "Tajikistan"},
  {id: "TZ", label: "Tanzania"},
  {id: "TH", label: "Thailand"},
  {id: "TL", label: "Timor Leste"},
  {id: "TG", label: "Togo"},
  {id: "TK", label: "Tokelau"},
  {id: "TO", label: "Tonga"},
  {id: "TT", label: "Trinidad and Tobago"},
  {id: "TN", label: "Tunisia"},
  {id: "TR", label: "Turkey"},
  {id: "TM", label: "Turkmenistan"},
  {id: "TV", label: "Tuvalu"},
  {id: "UG", label: "Uganda"},
  {id: "UA", label: "Ukraine"},
  {id: "AE", label: "United Arab Emirates"},
  {id: "GB", label: "United Kingdom"},
  {id: "US", label: "United States"},
  {id: "UY", label: "Uruguay"},
  {id: "UZ", label: "Uzbekistan"},
  {id: "VU", label: "Vanuatu"},
  {id: "VE", label: "Venezuela"},
  {id: "VN", label: "Viet Nam"},
  {id: "WF", label: "Wallis"},
  {id: "YE", label: "Yemen"},
  {id: "ZM", label: "Zambia"},
  {id: "ZW", label: "Zimbabwe"}
]
